import type { Company, Post } from "../types/types";

export const posts: Post[] = [];

export const companies: Company[] = [
  {
    id: "c1",
    name: "HanaLoop",
    country: "KR",
    emissions: [
      {
        yearMonth: "2025-01-01",
        source: "전기",
        description: "한국전력",
        emissions: 110,
      },
      {
        yearMonth: "2025-02-01",
        source: "전기",
        description: "한국전력",
        emissions: 112,
      },
      {
        yearMonth: "2025-03-01",
        source: "전기",
        description: "한국전력",
        emissions: 115,
      },
      {
        yearMonth: "2025-04-01",
        source: "전기",
        description: "한국전력",
        emissions: 130,
      },
      {
        yearMonth: "2025-05-01",
        source: "전기",
        description: "한국전력",
        emissions: 120,
      },
      {
        yearMonth: "2025-05-01",
        source: "전기",
        description: "한국전력",
        emissions: 101,
      },
      {
        yearMonth: "2025-06-01",
        source: "전기",
        description: "한국전력",
        emissions: 110,
      },
      {
        yearMonth: "2025-07-01",
        source: "전기",
        description: "한국전력",
        emissions: 120,
      },
      {
        yearMonth: "2025-08-01",
        source: "전기",
        description: "한국전력",
        emissions: 111,
      },

      {
        yearMonth: "2025-01-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 230,
      },
      {
        yearMonth: "2025-02-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 340,
      },
      {
        yearMonth: "2025-03-01",
        source: "원소재",
        description: "플라스틱2",
        emissions: 23,
      },
      {
        yearMonth: "2025-03-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 430,
      },
      {
        yearMonth: "2025-04-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 510,
      },
      {
        yearMonth: "2025-05-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 424,
      },
      {
        yearMonth: "2025-05-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 232,
      },
      {
        yearMonth: "2025-05-01",
        source: "원소재",
        description: "플라스틱2",
        emissions: 40,
      },
      {
        yearMonth: "2025-06-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 450,
      },
      {
        yearMonth: "2025-07-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 340,
      },
      {
        yearMonth: "2025-07-01",
        source: "원소재",
        description: "플라스틱2",
        emissions: 43,
      },
      {
        yearMonth: "2025-08-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 230,
      },

      {
        yearMonth: "2025-01-01",
        source: "운송",
        description: "트럭",
        emissions: 41,
      },
      {
        yearMonth: "2025-02-01",
        source: "운송",
        description: "트럭",
        emissions: 211,
      },
      {
        yearMonth: "2025-03-01",
        source: "운송",
        description: "트럭",
        emissions: 123,
      },
      {
        yearMonth: "2025-04-01",
        source: "운송",
        description: "트럭",
        emissions: 42,
      },
      {
        yearMonth: "2025-05-01",
        source: "운송",
        description: "트럭",
        emissions: 123,
      },
      {
        yearMonth: "2025-05-01",
        source: "운송",
        description: "트럭",
        emissions: 12,
      },
      {
        yearMonth: "2025-06-01",
        source: "운송",
        description: "트럭",
        emissions: 123,
      },
      {
        yearMonth: "2025-07-01",
        source: "운송",
        description: "트럭",
        emissions: 41,
      },
      {
        yearMonth: "2025-08-01",
        source: "운송",
        description: "트럭",
        emissions: 123,
      },
    ],
  },
  {
    id: "c2",
    name: "하나루프",
    country: "US",
    emissions: [
      {
        yearMonth: "2025-01-11",
        source: "전기",
        description: "한국전력",
        emissions: 1100,
      },
      {
        yearMonth: "2025-02-10",
        source: "전기",
        description: "한국전력",
        emissions: 112,
      },
      {
        yearMonth: "2025-03-09",
        source: "전기",
        description: "한국전력",
        emissions: 115,
      },
      {
        yearMonth: "2025-04-27",
        source: "전기",
        description: "한국전력",
        emissions: 130,
      },
      {
        yearMonth: "2025-05-18",
        source: "전기",
        description: "한국전력",
        emissions: 120,
      },
      {
        yearMonth: "2025-05-01",
        source: "전기",
        description: "한국전력",
        emissions: 1012,
      },
      {
        yearMonth: "2025-06-19",
        source: "전기",
        description: "한국전력",
        emissions: 110,
      },
      {
        yearMonth: "2025-07-01",
        source: "전기",
        description: "한국전력",
        emissions: 120,
      },
      {
        yearMonth: "2025-08-23",
        source: "전기",
        description: "한국전력",
        emissions: 111,
      },

      {
        yearMonth: "2025-03-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 230,
      },
      {
        yearMonth: "2025-01-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 340,
      },
      {
        yearMonth: "2025-04-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 340,
      },
      {
        yearMonth: "2025-04-21",
        source: "원소재",
        description: "플라스틱2",
        emissions: 23,
      },
      {
        yearMonth: "2025-03-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 430,
      },
      {
        yearMonth: "2025-07-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 51,
      },
      {
        yearMonth: "2025-05-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 424,
      },
      {
        yearMonth: "2025-05-05",
        source: "원소재",
        description: "플라스틱1",
        emissions: 232,
      },
      {
        yearMonth: "2025-05-01",
        source: "원소재",
        description: "플라스틱2",
        emissions: 40,
      },
      {
        yearMonth: "2025-06-08",
        source: "원소재",
        description: "플라스틱1",
        emissions: 450,
      },
      {
        yearMonth: "2025-07-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 340,
      },
      {
        yearMonth: "2025-07-01",
        source: "원소재",
        description: "플라스틱2",
        emissions: 43,
      },
      {
        yearMonth: "2025-08-01",
        source: "원소재",
        description: "플라스틱1",
        emissions: 230,
      },

      {
        yearMonth: "2025-01-31",
        source: "운송",
        description: "트럭",
        emissions: 41,
      },
      {
        yearMonth: "2025-02-01",
        source: "운송",
        description: "트럭",
        emissions: 211,
      },
      {
        yearMonth: "2025-03-09",
        source: "운송",
        description: "트럭",
        emissions: 123,
      },
      {
        yearMonth: "2025-02-01",
        source: "운송",
        description: "트럭",
        emissions: 42,
      },
      {
        yearMonth: "2025-03-01",
        source: "운송",
        description: "트럭",
        emissions: 123,
      },
      {
        yearMonth: "2025-05-01",
        source: "운송",
        description: "트럭",
        emissions: 12,
      },
      {
        yearMonth: "2025-06-01",
        source: "운송",
        description: "트럭",
        emissions: 123,
      },
      {
        yearMonth: "2025-07-01",
        source: "운송",
        description: "트럭",
        emissions: 41,
      },
      {
        yearMonth: "2025-08-01",
        source: "운송",
        description: "트럭",
        emissions: 123,
      },
    ],
  },
];
